### PR TITLE
feat: support .sync modifier

### LINKED ISSUE #15: support v-model
Instead of `:code` and `@change`, could you support `v-model` by using `value` and `@input` ? or maybe `:code.sync` with `code` and `@update:code` ?

### PR DESCRIPTION
**Pull request by jefrydco**
Fix #15

### CODE REVIEW

**Comment by koca** [comment]
Hey, thanks for the PR. 
But why do we need the sync modifier? If the default v-model events solves the problem than lets use `value` prop and `input` event instead of `code` prop and `change` event.
What do you think?

**Comment by jefrydco** [comment]
Yes, I agree with you. My consideration is if we change the `code` prop and `change` event, it would be a breaking change. Because they are the main communication between this package and the rest of the world.

**Comment by koca** [comment]
Yep you are right that would be a breaking change. I will merge this and we can release removed version with v1.0.0? Sounds good?

**Comment by jefrydco** [comment]
> I will merge this and we can release removed version with v1.0.0?

You mean that we can change the`code` props and `change` event with `value` props and `input` event, then release them with `v1.0.0`? If it yes, sounds good to me.

**Comment by koca** [comment]
Actually I was thinking about two options:
1 - merge this and publish v0.4.0. (this evening)
2 - merge this and publish v0.4.0 and remove `.sync` on the v1.0.0 release (I'm planining to release next weekend).

I'll go with the second option. I'm merging this and releasing a new version. Next week v1.0.0 i will deprecate for the sake of proper v-model.

**Pull request merged**
