### PR TITLE
feat: next version

### PR DESCRIPTION
**Pull request by koca**
Next version of vue-prism-editor 

New features 
Fixes
9kb to ~3kb gz

### CODE REVIEW

**Comment by koca** [comment]
Fixes:
#71 custom `higlight` fn
#49 fixed
#73 fixed
#72 fixed
#43 fixed
#70 fixed
#62 #65 fixed
#67 custom `higlight` fn
#41 fixed
#28 fixed

**Comment by koca** [comment]
fixes #79

**Comment by lane-c-wagner** [comment]
Nice! Let's get er done :) This is one of the last things I'm waiting on to take https://classroom.qvault.io out of the sandbox

**Comment by MattIPv4** [comment]
@koca is there an ETA for when this will be merged/released?

**Comment by koca** [comment]
Hey @MattIPv4! Tomorrow i'll try to release a new version.
cc @lane-c-wagner

**Comment by koca** [comment]
Hi guys! Released a beta version of v1 🎉

Try now: `vue-prism-editor@1.0.1-beta.2` 

There are breaking changes so please read the readme in https://github.com/koca/vue-prism-editor/tree/feature/next

cc @MattIPv4 @lane-c-wagner @elevatebart 
If you need help or have ideas just let me know 😊

btw next version is just 2.7kb gzip 🚀 (previously ~7-9kb gzip)
editorv1-size

**Comment by koca** [comment]
example codesandbox using the next version: https://codesandbox.io/s/vue-prism-editor-next-gzi7k

**Comment by MattIPv4** [comment]
Hey @koca,

I'm having a lot of selector power issues (existing styling framework is overriding your textarea styles).

Could I suggest writing the styling in scss, so that you can more easily nest the selectors to give them more power (and so I can import the styles directly in our scss at the right point to give them even more power)?

**Comment by lane-c-wagner** [comment]
Looks great @koca ! Thanks for working on this. If you want to see what we are building with your library check it out: https://classroom.qvault.io
Or the playground:
https://classroom.qvault.io/playground/go

**Comment by koca** [comment]
> Hey @koca,
> 
> I'm having a lot of selector power issues (existing styling framework is overriding your textarea styles).
> 

So you are having a css spesificity issue on textarea, interesting 🤔. Thanks for the info!

> Could I suggest writing the styling in scss, so that you can more easily nest the selectors to give them more power (and so I can import the styles directly in our scss at the right point to give them even more power)?
> 
> Something like: https://gist.github.com/MattIPv4/3939e6c7079866260181d88864fa5561

I'm not sure about supporting scss but we can do nesting with postcss to fix the spesificity. You can still import `css` in `scss` so that would work. Thank you! 😊

**Comment by koca** [comment]
> Looks great @koca ! Thanks for working on this. If you want to see what we are building with your library check it out: https://classroom.qvault.io
> Or the playground:
> https://classroom.qvault.io/playground/go

Love it! Just checked the js course looks promising ✌️ Where do you run the code client/backend?

**Comment by lane-c-wagner** [comment]
@koca The Go code runs using web assembly, and the JavaScript is executed right in the browser

**Comment by koca** [comment]
> @koca The Go code runs using web assembly, and the JavaScript is executed right in the browser

Running go code on browser using web assembly? 🚀 Cool! Is it open source?

**Comment by lane-c-wagner** [comment]
Yeah here is a tutorial: https://qvault.io/2020/07/01/running-go-in-the-browser-with-web-assembly-wasm/

You can also hop in our discord if you want to stay in the loop https://qvault.io

**Comment by lane-c-wagner** [comment]
@koca What are we waiting for on this version?

**Comment by lane-c-wagner** [comment]
@koca I love this library, but I'm really needing that spacing change! Is there anything I can do to help get this next release out?

**Comment by koca** [comment]
@lane-c-wagner been busy sorry 🙏. Actually i was waiting for feedbacks but seems like other guys are busy as well :D anyway just released official v1 release 🎉.  Enjoy and thanks for the love mate ♥️ 👍  
Please let me know if you need any help.

**Comment by nikocraft** [comment]
Thank you, I will update my CMS to use the latest version! Keep up the great work! I'll let you know how it works, when I get around to do this.

**Comment by lane-c-wagner** [comment]
@koca Thanks so much! New "Practical Cryptography" and "Go Mastery" courses are going to be some much better now :) https://classroom.qvault.io/dashboard/courses

**Comment by koca** [comment]
classroom.qvault.io so good 🚀 cant try the courses(need to pay) but tried the free one and love the clean design! 🚀

btw vue-prism-editor code and version is correct on NPM, seems like i just need to update the readme. Maybe i can't see, can you tell me what is missing?

**Comment by lane-c-wagner** [comment]
I got it working, I was just confused about NPM. My bad!

If you want to check out another course or two use this code to get some free gems: `3CORBL` @koca Thanks for the awesome library

**Comment by elevatebart** [comment]
@koca, you rock my socks... In other words, it works and vue-live is now awesome ! Thank you ;)

**Comment by koca** [comment]
haha thanks @elevatebart! We use `vue-live` in @chakra-ui it works great 👍
cheers @lane-c-wagner! and thank you for the coupon 😇

**Pull request merged**
