### PR TITLE
fix: make sure the language class is kept after first render

### LINKED ISSUE #30: After a change to content, editor loses language.
Great tool !! Thank you.

Just a little minor quirk.
On load, the DOM looks like this:

```html
<pre spellcheck="false" autocapitalize="off" autocomplete="off" autocorrect="off" data-gramm="false" class="prism-editor__code  language-html" style="border-top-left-radius: 0px; border-bottom-left-radius: 0px;" contenteditable="true">
  <code class=" language-html">
  <!-- My Code -->
  </code>
</pre>
```

as soon as I start typing in the editor, the `language-html` class of `<code>` is dropped. This would not be an issue if vuepress was counting on this class for its styling of vue code.

I will try to find the cause.

### PR DESCRIPTION
**Pull request by elevatebart**
closes  #30

### CODE REVIEW

**Comment by koca** [comment]
Did you run the tests? They are failing ^^

**Comment by elevatebart** [comment]
I did not... oops!! will do tonight

**Comment by elevatebart** [comment]
I did update the test. I also took the liberty to use the [`toMatchInlineSnapshot()`](https://jestjs.io/docs/en/snapshot-testing#inline-snapshots) assertion. I am sure you will find it to your liking

**Comment by koca** [comment]
Thank you for the PR and LGTM :) i will merge and publish a new version.

**Pull request merged**
